emlog/emlog

content/templates/default/css/main.css, content/templates/default/footer.php, content/templates/default/header.php, content/templates/default/log_list.php, content/templates/default/module.php
=> Work In Progress

content/templates/default/css/main.css, content/templates/default/echo_log.php, content/templates/default/module.php, content/templates/default/page.php
=> 调整一些UI上的细节

content/templates/default/css/main.css, content/templates/default/module.php
评论及评论区的显示、分页、overflow、日历、markdown、小导航等
=> 调整了一些小屏幕上显示的细节

admin/views/article_write.php, admin/views/css/style.css, admin/views/header.php, admin/views/page_create.php, include/model/log_model.php
=> 修复了编辑器一些问题

admin/views/article_write.php, admin/views/css/style.css, admin/views/page_create.php, include/model/log_model.php
=> 关于编辑器的一些配置

config.sample.php, include/lib/database.php, include/lib/mysqlpdo.php
=> 增加mysql的pdo方式连接，mysql配置项增加端口的设置

admin/views/article_write.php, admin/views/footer.php, admin/views/header.php
=> 更新缓存和修复bug

admin/views/article_write.php, admin/views/js/common.js, admin/views/page_create.php, content/templates/default/css/main.css, content/templates/default/page.php
钩子先去掉吧，等我先测试并未来几日内做一个成功的emlog插件————编辑器及前台支持LaTeX公式的插件再添加上。
=> 去掉js钩子，待优化

admin/editor.md/editormd.js, admin/views/article_write.php, admin/views/js/common.js, admin/views/page_create.php, content/templates/default/css/main.css, content/templates/default/js/common_tpl.js, content/templates/default/page.php
添加了编辑器js钩子
编辑器改为更人性的single滚动
前台一些细节上的优化
=> 添加了编辑器js钩子和一些日常前端调整

content/templates/default/css/markdown.css, content/templates/default/css/style.css, content/templates/default/js/common_tpl.js, content/templates/default/js/zoom.js, content/templates/default/log_list.php
- 使 Toc 根据文章阅读位置来调整 toc 滚动条位置（目录跟踪）
- 在移动端隐藏时分
- 调整小屏下边距和文章数据的左右占比
=> 目录跟踪和调整移动端显示

admin/views/article_write.php, content/templates/default/css/style.css
调整了css代码外观
一个显示上的小bug
搜索黑框高度值，优先以Chrome浏览器为基准
裁剪框，使用插件内置Data属性，指定一个静态的背景，使其不点击背景就关闭，完美解决裁剪关闭问题
=> 主要是解决裁剪关闭问题

admin/views/article.php
Just fix the wrong typing in code
=> Fix mistype in html

include/lib/option.php, install.php
Correct the function name getDefPluin() to getDefPlugin()
=> Fix a mistype: pluin -> plugin

content/templates/default/404.php, content/templates/default/header.php
Convert meta charset to HTML5 format
=> Fix meta charset

include/lib/parsedown.php
Capitalize the first letter of the class name according to PSR
=> Capitalize parsedown class name

admin/views/css/css-main.css, admin/views/user.php, content/templates/default/css/markdown.css, content/templates/default/css/style.css, content/templates/default/echo_log.php, content/templates/default/log_list.php, content/templates/default/module.php
后台：
1. 后台的用户搜索框优化了点
前台：
1. 顶部导航和文章列出对齐了
2. markdown 增加了两端对齐，会让文章更美观
3. 其他一些小细节
=> 简单优化了一点前端显示

admin/views/css/css-main.css
=> 修复移动端在菜单隐藏时，菜单某些情况下依然可见的显示问题

admin/views/index.php
Invalid html tag "sapn" -> span
=> Fix a tag mistype

include/lib/function.base.php, install.php
Replace old html4 meta charset with new html5 format
=> Reformat meta charset to HTML5

include/lib/storage.php
=> Fix SQL Query syntax in lib/storage.php

content/templates/default/footer.php
=> fix：修复模版足部信息显示不正常的问题

content/templates/default/module.php
就是这玩意，以前没有 href 。一直以为是自然现象，原来它可以有 href 的。
=> fix:顶部导航，有子菜单的选项，父菜单不可点击选择的 bug

admin/views/article_write.php, admin/views/js/common.js
System background:
- Fixed a problem，the failure of [More Option] cookies used.
=> fix:failure of [More Option] cookies uses

admin/editor.md/editormd.js, admin/views/article_write.php, admin/views/css/css-main.css, admin/views/js/common.js, content/templates/default/css/style.css, content/templates/default/js/common_tpl.js, content/templates/default/module.php
System background:
- The Editormd could support the full-screen mode (just added a line code of CSS)
- A detail of Editormd. When mobile device user slides the screen by finger, touch Editormd's toolbar accidentally, the tool will take effect. Very annoying (So I disable the tool take effect when the user slides the screen by finger)
- The Page-Create page can be left without alert when user has saved their content.
- [More Option] display effect optimization.
Default Template
- fix the "replay comment bug" that the User can't replay other people in the comment area in the Default Templates.
- fix "toc" effect optimization in Chrome browser open page in new target mode.
- Add some CSS var of color (Of course, it's not finished yet), prepare for night mode.
- Add some HTML "title" value, …
=> fix:Editormd mobile device bug, some optimization and add Editormd full-screen mode, etc.

content/templates/default/css/style.css, content/templates/default/js/common_tpl.js, content/templates/default/js/zoom.js, content/templates/default/log_list.php, content/templates/default/module.php
Default templates:
I made some minor adjustments.
When a long zoom image is displayed, the user may need to scroll the mouse, causing the screen position to change. Therefore, I created a variable to record the scrollbar position. When the user closes the zoom image, the scrollbar position will be restored.
Of course, my commit may be a bit messy, but I only added three lines - 61, 105, and 175. I'm not sure why.
And other change..... I received some advice from a lighthouse, but I don't think it's very useful.
=> feat:When clicking on the zoom image, the scrollbar will return to its original position.

admin/views/auth.php
Fix html semantics in auth.php:
<ul&gt;
<li&gt;</li&gt;
</ul&gt;
=> Fix html semantics in auth.php

content/plugins/tips/tips.php, content/plugins/tips/tips_callback.php, content/plugins/tips/tips_setting.php, content/plugins/tpl_options/tpl_options.php, content/plugins/tpl_options/tpl_options_callback.php, content/plugins/tpl_options/tpl_options_setting.php, content/plugins/tpl_options/views/setting.php, content/plugins/tpl_options/views/templates.php, content/templates/default/footer.php, content/templates/default/module.php, include/lib/calendar.php, include/lib/common.php, include/model/log_model.php, include/model/media_model.php
=> Replace Tab with 4 spaces

include/service/notice.php
=> fix: 修正错别字

content/plugins/tpl_options/assets/main.js, content/plugins/tpl_options/tpl_options.php
1. 修正css引起的空白
2. 减少textarea的行数
=> fix:模板设置插件-修复样式错误

admin/views/index.php
=> feat:优化后台更新后逻辑

admin/page.php
admin/views/page_create.php: Variable $mediaSorts is not defined
=> Fix a bug in admin/views/page_create.php

admin/sort.php, admin/views/sort.php, include/model/sort_model.php, install.php
=> feat: Sort supports image
