admin/views/article_write.php
admin/views/css/css-main.css
admin/views/header.php
admin/views/js/sb-admin-2.min.js
admin/views/page_create.php
content/templates/default/css/main.css
content/templates/default/js/common_tpl.js
content/templates/default/module.php

-  个人资料下面的空白略减一些
-  最新评论的评论文本略向右移
-  配合js优化了导航的下拉框
-  添加了$dp_id,用来表示下拉框的编号，以便js操作更准确。
- 简化了计算导航下拉框写法。也避免了一些错误。也可自定义宽度了。
- 重写了后台的模版js，主要是优化了调出菜单动画，以及二级菜单显示的一些问题。
- 解决“外观”“系统”对不齐的问题。并添加emlog_title的类名，以便后续优化。
- 主要是电脑端固定，手机端菜单左滑后固定页面，以及其余一些微调。
- 默认在大屏模式下显示预览
- 去掉了多余的代码，然后添加了“在大屏模式下，编辑器默认显示预览”

前台和后台的一些前端显示调整

---

admin/views/article_write.php
admin/views/js/common.js
admin/views/page_create.php
content/templates/default/css/main.css
content/templates/default/css/markdown.css

- 既然模版又做了调整，那就顺便进一步优化一下模版吧。（markdown样式问题修复、显示头像、头像长宽显示问题修复）
- 添加了保存快捷键 [ ctrl ( cmd ) + s ]
- 添加了js钩子。可以通过在header.php部的钩子，引进JaveScript代码，对common.js中的editorHook()函数进行覆盖，实现编辑器的扩展操作。
如在header.php头部的钩子里可以这样写
```
echo'
<script>
function editorHook(sort) {
if(sort==article) {
//下面两行相当于在编辑器配置处（或钩子所在处）执行，具体操作查阅编辑器文档
Editor.executePlugin("your_Plugin", "/content/plugins/test/your_plugin");//加载你的插件
Editor.yourPlugin();//执行你的插件
}
}
</script>
';
```

前台模版的优化，保存快捷键，编辑器添加js钩子

---

admin/index.php

There is a duplicated code line in admin/index.php in lines 42 & 46:
`header('Content-Type: application/json; charset=UTF-8');`
I offer to use it only once for the code minimization!

get_news - Use header() only once

---

content/templates/default/header.php
content/templates/default/js/common_tpl.js

比如 emlog.com/fenlei/1.html   ,这个时候 js 刷新时，会以 emlog.com/fenlei/  而不是 emlog.com/为根目录寻找验证码php ，进而无法显示新验证，现在修复了这个问题。。
另外优化了 显示验证码的逻辑。

修复伪静态下，评论验证码可能无法刷新的bug

---

admin/views/article.php
admin/views/comment.php
admin/views/css/css-main.css
admin/views/js/common.js

[fix:后台的评论回复模态框加上了自动换行](https://github.com/emlog/emlog/commit/421430f3f71e935c26ab59a76167d11be87d406d)[](https://github.com/kohunglee)
比如评论为 ‘sssss......’ （几百个 s）时，可以自动换行
[fix:使搜索框与用户搜索界面保持一致](https://github.com/emlog/emlog/commit/4c0d89288256f1e491c2a1e18b8d215ce7d0c1fe)[](https://github.com/kohunglee)
（口误，在 commit 的注释中写错了，应该是 *用户搜索界面*）
[fix:去除了清理标签，因为已经经过转义，没必要了](https://github.com/emlog/emlog/commit/22e4ebab894f1b3ab93fe1c14a67215c93fba888)
即使是默认的 stay hungry ，stay foolish 这句评论，在回复时的模态框，也会变成 stayhungrystayfoolish

评论回复加自动换行、搜索框优化、去除后台评论回复时转义评论内容操作

---

admin/views/article.php
admin/views/css/css-main.css
admin/views/user.php

1. 优化之前解决搜索框换行问题的方法。
因为 “form-inline” 这个 class 很多地方都在用，其中一些地方不适合直接 width:100% 和整体化（且不自动换行），所以新建一个 class “search-inputs-nowrap” ，只作用于这两个搜索框，完美解决它们在移动端身首分离的问题。
2. 上午解决页面高度的方法并不完美，现在决定加个初始高度 100vh ，以避免它们在超长手机上显示时出现高度不足的问题

fix:移动端页面高度以及搜索框前端显示问题

---

admin/editor.md/plugins/help-dialog/help-dialog.js
admin/views/article_write.php
admin/views/css/css-main.css
admin/views/header.php
admin/views/page_create.php
content/templates/default/css/style.css
content/templates/default/echo_log.php
content/templates/default/footer.php
content/templates/default/header.php
content/templates/default/js/common_tpl.js
content/templates/default/log_list.php
content/templates/default/module.php
content/templates/default/page.php
content/templates/default/side.php

前台:
1. 修正代码使其完全符合 W3C 验证器
2. 边栏”标签“的边框删去
后台：
1. 大屏情况下，顶部的白色菜单栏高度与左边栏的水平线对齐
2. 顶部的白色菜单栏增加了轻微的透明磨砂效果，以削弱空间紧迫感
3. 编辑器初步增加了使用帮助的图标，向用户提供 markdown 语法帮助、说明一些快捷键

修正代码使其完全符合 W3C 验证器、后台顶栏美化和编辑器添加帮助图标

---

admin/setting.php
admin/views/setting_mail.php

upgrade SMTPSecure fix not support STARTTLS method like Outlook mail smtp
修复原有的邮件通知不支持 Outlook 邮箱的 587端口的STARTTLS加密方式。
上述修改我已经自己测试是 OK 的，那多或者其他人可以测试下。
也可以只改动 setting.php 将 https://github.com/emlog/emlog/blob/ee8f3c5b93ee9000294ec92b7ae90bdee5bdd5b1/admin/setting.php#L308 注释掉，改成如下这样，增加一行判断也可以：
```php
//$mail->SMTPSecure = 'ssl';                             // 设置使用 ssl 加密方式登录鉴权
if ($data["smtp_port"] == '587') $mail->SMTPSecure = 'STARTTLS';
```
不过这种方式不推荐 不够灵活。

Update setting_mail.php and setting.php

---

admin/editor.md/plugins/table-dialog/table-dialog.js

此是之前，将编辑器的对话框工具定义在一个不被 后台 顶栏遮挡的地方后，遗留的小问题。
其他工具都已经一一被解决，但不慎忘掉还有一个表格没解决￣□￣｜｜。解决方式就是重新定义程序中 editor 的元素。
还是一样的配方。

修复编辑器表格多次点击的 bug

---

admin/views/js/common.js
content/templates/default/js/common_tpl.js

前台
1. 添加了图片判断 undefined。如果文章中某个图片不存在 <a> 标签，那么 js 会报错
后台
1. 调换了粘贴图片时，原图和略缩图的位置。以前，粘贴图片会发生图片在前台默认显示原图，但点击后是略缩图的情况。

修复图片相关的两个问题

---

content/templates/default/css/style.css
content/templates/default/footer.php
content/templates/default/js/common_tpl.js

1. [修复在图片多的文章里，toc 定位出错的问题](https://github.com/emlog/emlog/commit/94c65202dda61e9131e95bfc7c91d80ddac96dd5)
之前，如果文章中有大量图片的话，如何设置 toc 那么会出现目录定位不准的情况。现在解决了，方式是每隔 1.5s  重新更新一番 toc 内部的数据
2. [去除在不设置 ICP 备案下，默认模版足部多余的 a 标签](https://github.com/emlog/emlog/commit/5b581c20ccf37e54372440ff9f42e90f12fe5ea7)
由群友反馈的建议。如果不设置 ICP ，多一个 ICP 的空 a 标签确实很多余。

对自带模版的细节优化

---

include/model/media_model.php

问题根源是，这个地方的替换字符多了几个空格。
在之前
修改这里的代码后
另外，经过测试，七牛云插件启用后，不受影响。

fix：修复编辑页面，插入图片略缩图和高清图链接不对，出错问题

---

admin/views/css/css-main.css
admin/views/js/common.js
admin/views/page_create.php
content/templates/default/css/style.css
content/templates/default/footer.php

后台：
1. 后台顶部那个菜单栏，感觉把 position ：fixed 去掉后，操作体验一下子阔朗起来。感觉这样更好。
2. 页面编辑器之前是没有自动保存的，（因为还要为它定制个保存函数，懒），现在先简单加上了
前台：
3. 前台代码日常优化，没什么可说的

feat：后台“页面”默认编辑器添加快捷键自动保存

---

admin/views/article_write.php
admin/views/css/css-main.css
admin/views/js/common.js
admin/views/page_create.php
content/templates/default/css/style.css
content/templates/default/header.php
content/templates/default/js/common_tpl.js
content/templates/default/log_list.php
content/templates/default/module.php

后台：
- 页脚加上了白色背景，（多少会有点好看吧）
- 编辑页面（文章、页面）全局可使用快捷键 Ctrl（Cmd）+ S 来保存内容。（过去只能在光标在编辑器内，按快捷键才行）
前台：
- 加上了白色页脚背景（比较，如果习惯了桌面网页的人，页头页脚的独特显示性还是很重要的）
- 归档改为下拉框（内容特别多的话，这样会优雅一些）
- 文章列出页，添加「编辑」快捷链接（方便编辑和修改文章）
- 网页副标题的优化，在其内容过多时，截取一番。

feat:页脚背景、后台编辑页面全局快捷键保存、优化前台体验

---

content/templates/default/css/style.css
content/templates/default/log_list.php
content/templates/default/module.php

1.  文章列出页的「编辑」，在移动端显示可能会因换行而不美观。所以放在右面的浏览量后了。
2. 把评论区头像的 alt 加上了、把回复、取消回复 这些由 < a > 换成了 < button >

fix:模版的一些日常微调

---

content/templates/default/css/style.css
content/templates/default/log_list.php
content/templates/default/module.php

1. 删掉一些在一些编译器出现异常的 CSS
2. 修复了前几日引入的一些前端致命 BUG (评论头像、文章列出页的「编辑」显示异常等)
文章列出页的「编辑」，还是决定放到左边，而且直接在移动页面隐藏。因为在移动端的下面的文章 info 实在空间太小了。而且移动端对这个的必要性不大，因为手机浏览器没有很清晰的标签页概念。

fix:删去一些异常代码、修复若干前几天引入的 BUG

---

content/templates/default/css/style.css
content/templates/default/js/common_tpl.js
content/templates/default/module.php
include/lib/function.base.php

核心：
- 为系统头像函数添加「单次接管式钩子」，方便「插件」对「评论区头像」进行控制
- 将原有的镜像地址更改为 Cravatar.cn，既使头像输出稳定，又方便国内用户进行头像申请与注册
模板：
- 日常修修改改
示例：插件对系统头像的控制方式：
插件中可写如下代码
```php
addAction('get_Gravatar', 'change_gravatar');
function change_gravatar($email, &$gravatar_url) {
// 在这里写逻辑，更换 qq 啊什么，是不是注册用户什么的.....
// $email 就是邮箱地址
// 反正最终让 $gravatar_url 等于自己整理好的地址就行了
// 比如下面两行代码：
$hash = md5($email);
$gravatar_url = "//sdn.geekzu.org/avatar/$hash?s=$s";
return true;
}
```
**应注意**，这是「单次接管式钩子」，「单次接管式钩子」上只能挂一个函数，也就是说，如果我们有多个插件，都调用了这个钩子，那系统运行到这个钩子处，只运行挂在上面的第一个函数。（换言之，这么多插件不能都起效，只有第一个插件有效。）

feat:为「系统头像函数」添加「单次接管式钩子」，方便「插件」对「评论区头像」进行控制

---

content/templates/default/css/style.css
include/lib/common.php

I optimized the emlog core lib paging function. 
If our total page number is less than 7 (2 ~ 6), then it will return all the page links. 
If our total number of pages is less than 12 and more than 6 (7 ~ 11), then it will returns the result as follow.
If our total number of pages is more than 11 (12 ~ + infinity), then it will return the result as follow.

feat:More powerful paging function

---

content/templates/default/js/zoom.js

Sometimes, our blog posts contain long images that, when clicked by a user, cause problems：
The image zooms in, centered, and if scrollTop < the height of the image outside the screen, the entire image cannot be displayed by scrolling. 
Therefore, I have made a fix: 
If the screen is unable to display the entire enlarged image, we will align the top edge of the enlarged image with the top edge of the screen.
issue source：https://emlog.cn/post-633.html

fix:Optimization of long image in zooming in

---

content/templates/default/css/style.css
content/templates/default/js/common_tpl.js
content/templates/default/module.php

In my last commit, I fixed an issue with the default template comment area where the ID name "comment-place" was not appropriate. This was because `line 65 in "include/model/comment_model.php"` specifies that if a user clicks the pagination button to view the next page of comments, the URL will have "#comments" appended to it.

fix:CSS variable name conflict and make an appropriate name

---

admin/article.php
admin/views/article_write.php
admin/views/css/css-main.css
content/templates/default/css/style.css
content/templates/default/js/common_tpl.js
rss.php

I optimized the XML structure of RSS. I used https://validator.w3.org/feed/ to validate rss.php and found some issues that required adjustment.
I found that HTML5 < input type="datetime-local" > is very suitable for the date setting in the article edit page.
The main update is that the toc can now be closed on large screens.
------------
**核心**：根据  https://validator.w3.org/feed/  这个验证器的提示，优化了 RSS 的输出结构。
**后台**：文章编辑页面的日期选择那个表单，变成了 < input type="datetime-local" > 这个 HTML5 表单。很合适。（当然，我把 秒 这个参数掐去了，因为会产生一些 bug。其实发现在别的地方也用不着。）
**模板**：最主要的是，toc 在桌面端可以关闭了。

fix:Optimized the XML structure of RSS and some other core adjustment

---

admin/article.php

[fix] When editing an article, the resource classification cannot be obtained correctly

---

include/model/log_model.php

支持在`log_list.php`里使用
```
$value['sort']
$value['taglist']
$value['authorinfo']
```
以及在`echo_log.php`里使用
```
$sort
$taglist
$authorinfo
```
分别输出**分类**、**标签**、**作者信息**。
1. `sort`是一个array，包含`name`（分类名）和`url`（此分类的网址）
2. `taglist`是一个**二维**array，包含该文章所有tag，每个tag下都是一个array，内含`name`（标签名）和`url`（该标签的网址）
3. `authorinfo`是一个array，包含：
- `username`（用户名）
- `nickname`（用户昵称）
- `name_orig`（未进行HTML 转义的昵称）
- `email`（电邮地址）
- `photo`（头像）
- `description`（备注）
- `role`（用户组）
- `ischeck`（内容是否需要管理员审核）
- `state`（用户状态0正常1禁用）
- `ip`（作者ip）
- `url`（查看该作者所有文章的网址）

为log_list.php和echo_log.php加入sort taglist authorinfo的变量支持。

---

admin/views/article_write.php
admin/views/js/common.js
admin/views/uc_header.php
content/templates/default/css/markdown.css
content/templates/default/js/common_tpl.js
content/templates/default/module.php
include/model/comment_model.php

后台：
1. 将一些提示框改为了 layui 的提示框，删除一些无用的 js
2. 普通用户的后台的左上的「首页」链接，改成了 `<?= BLOG_URL ?>`，因为会有些人不在根目录安装 emlog
3. 后台回复评论，使用的是 coment_modal 里的 replyComment() ，但是很奇怪，里面不传入 邮箱地址，这导致前台无法显示头像。
（另外，开始评论审核模式时，后台普通用户在回复其他人的评论时，不会进入审核阶段，这和前台普通用户回复评论的结果是不一样的，不知这是 feat 还是 bug？）
模板：
1. 主要是将多年的 bug 给修了下，此后 有下拉框（子链接）的自定义的链接，可以点击了。
2. 一些简单的代码调整
--------
Backend:
1. Converted some prompts to Layui's prompts and removed some unused JavaScript files.
2. Changed the "Home" link in the upper left corner of the backend for regular users to `<?= BLOG_URL ?>`, as some people did not install emlog in the root directory.
3. When replying to comments in the backend, it uses the replyComment() function from coment_modal, but strangely, it does not pass in the email address, which leads to the inability to display avatars on …

fix: backend responses by adding missing avatars & other minor details.

---

admin/page.php
admin/views/page_create.php

功能描述以及使用场景：
1. 在写页面或编辑页面的时候，可以给页面增加标签(跟文章标签一致)
2. 标签会显示到页面的keywords元信息(跟文章一致)
3. 模版开发者可根据关键字，在页面调用其它相关文章来推荐文章
4. 模版开发者可根据关键字，将一系列页面聚合在一起（类似"页面分类",小众需求）

在写页面或编辑页面的时候，可以给页面增加标签
